# reference: https://docs.codecov.io/docs/codecovyml-reference
codecov:
  branch: master
  notify:
    after_n_builds: 10
comment: false

coverage:
  status:
    project:
      default:
        target: '82'
    patch:
      default:
        target: '50'

github_checks:
    annotations: false
